name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: |
        dotnet test --configuration Release --no-build --collect="Code Coverage" src\Ninject.Test
        nuget install Microsoft.CodeCoverage -x -Verbosity quiet
        for /f %%G in ('dir /b /s *.coverage') do Microsoft.CodeCoverage\build\netstandard1.0\CodeCoverage\CodeCoverage analyze /output:%%~dpnG.coveragexml "%%G"
        nuget install Codecov -x -Verbosity quiet
        for /f %%G in ('dir /b /s *.coveragexml') do Codecov\tools\codecov -f "%%G"
        
      
